name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Dev-2
  pull_request:
    branches:
      - main
      - Dev-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Ecommerce/Ecommerce.sln

    - name: Build
      run: dotnet build Ecommerce/Ecommerce.sln --no-restore

    - name: Run tests
      run: dotnet test Ecommerce/Ecommerce.sln --no-build --verbosity normal
